const twitterDummyData = {
  profiles: [
    {
      userID: 'u1',
      username: 'elonmusk',
      displayName: 'Elon Musk',
      bio: 'Mars, Cars, Chips, Starships. Tweets are my own.',
      avatar: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png',
      followers: ['u2', 'u3'],
      following: ['u2'],
      joined: '2010-06-02T12:00:00Z',
    },
    {
      userID: 'u2',
      username: 'catlady13',
      displayName: 'Cat Lady',
      bio: 'All things cats. Cat memes, cat facts, cat pics.',
      avatar: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png',
      followers: ['u1'],
      following: ['u1', 'u3'],
      joined: '2015-09-14T09:30:00Z',
    },
    {
      userID: 'u3',
      username: 'historybuff',
      displayName: 'History Buff',
      bio: 'History is written by the victors.',
      avatar: 'https://abs.twimg.com/sticky/default_profile_images/default_profile_400x400.png',
      followers: ['u2'],
      following: ['u1'],
      joined: '2018-01-22T17:45:00Z',
    },
  ],
  communities: [
    {
      communityID: 'c1',
      name: 'Space Enthusiasts',
      description: 'All about rockets, planets, and the universe.',
      members: ['u1', 'u3'],
      created: '2021-03-01T10:00:00Z',
    },
    {
      communityID: 'c2',
      name: 'Cat Lovers',
      description: 'Share your best cat moments!',
      members: ['u2'],
      created: '2022-07-15T15:30:00Z',
    },
  ],
  posts: [
    {
      postID: 't1',
      content: 'Just launched another rocket! 🚀',
      postedBy: 'u1',
      postedDate: '2025-08-25T14:00:00Z',
      communityID: 'c1',
      replyIDs: ['r1', 'r2'],
      likeUserIDs: ['u2', 'u3'],
      retweetUserIDs: ['u2'],
    },
    {
      postID: 't2',
      content: 'My cat just knocked over my coffee. Again.',
      postedBy: 'u2',
      postedDate: '2025-08-26T09:15:00Z',
      communityID: 'c2',
      replyIDs: ['r3'],
      likeUserIDs: ['u1'],
      retweetUserIDs: [],
    },
    {
      postID: 't3',
      content: 'Did you know the Roman Empire lasted over 1,000 years?',
      postedBy: 'u3',
      postedDate: '2025-08-27T08:00:00Z',
      communityID: 'c1',
      replyIDs: [],
      likeUserIDs: ['u1', 'u2'],
      retweetUserIDs: [],
    },
  ],
  replies: [
    {
      replyID: 'r1',
      postID: 't1',
      content: 'Congrats! When is Mars?',
      repliedBy: 'u3',
      repliedDate: '2025-08-25T14:05:00Z',
      likeUserIDs: ['u1'],
    },
    {
      replyID: 'r2',
      postID: 't1',
      content: 'Amazing! 🚀',
      repliedBy: 'u2',
      repliedDate: '2025-08-25T14:10:00Z',
      likeUserIDs: [],
    },
    {
      replyID: 'r3',
      postID: 't2',
      content: 'Classic cat move!',
      repliedBy: 'u3',
      repliedDate: '2025-08-26T09:20:00Z',
      likeUserIDs: ['u2'],
    },
  ],
};